server:
  port: 8080
spring:
  application:
    name: "quizzy"
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_db_aditya
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    sql:
      init:
        mode: always
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect



